# Generated by Django 4.2.4 on 2023-08-15 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelChopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('tel_haqida', models.TextField()),
                ('creat_date', models.DateTimeField(default=datetime.datetime.now)),
                ('update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('del_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Chop',
            },
        ),
    ]
